name: Kentyou Default CI Build

# Kentyou Default CI Build
#
# Automates Java builds and tests for commits to main branch and PRs,
# using JDK 17 and caching Maven dependencies.
#
# Deploys artifacts to GitHub Packages on main branch commits.
#
# Note: Ignores all tags as they are checked and built
#       using the tag-publish.yml workflow.
#
# The "source" version of this workflow is in our .github repository.

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: CI Build
      uses: kentyou/build-automation/actions/maven-build@618c22447eb725db457b9bf0d47398e52f5c5c7a # v1.0.0
      with:
        deploy-gh-packages: ${{ github.ref == 'refs/heads/main'}}
        repo-secret: ${{ secrets.KENTYOU_CI_PAT }}

