name: Build and publish a release Tag

# Build and deploy a tag, unless it is already deployed
# Do not build the main branch or pull requests. as they
# are checked and built in the ci-build.yml

on:
  push:
    tags: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Check Existing Deploy
      uses: kentyou/build-automation/actions/maven-deploy-check@618c22447eb725db457b9bf0d47398e52f5c5c7a # v1.0.0
      with:
        module-path: parent
        tag-name: ${{ github.ref_name }}
        cancel-workflow: true
        repo-secret: ${{ secrets.GITHUB_TOKEN }}
    - name: CI Build
      uses: kentyou/build-automation/actions/maven-build@618c22447eb725db457b9bf0d47398e52f5c5c7a # v1.0.0
      with:
        deploy-gh-packages: true
        release-version: true
        version-qualifier: .${{ github.ref_name }}
        repo-secret: ${{ secrets.KENTYOU_CI_PAT }}
